# Generated by Django 5.1.15 on 2026-03-15 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaverKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, unique=True)),
                ('term_count', models.IntegerField(default=0)),
                ('terms', models.JSONField(blank=True, default=list)),
                ('total_count', models.IntegerField(default=0)),
                ('naverpay_count', models.IntegerField(default=0)),
                ('price_compare_count', models.IntegerField(default=0)),
                ('last_searched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'naver_keyword',
            },
        ),
        migrations.CreateModel(
            name='NaverTrackingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_ids', models.JSONField(default=list)),
                ('schedule_type', models.CharField(choices=[('daily', '매일'), ('interval', '간격')], max_length=20)),
                ('schedule_time', models.CharField(blank=True, default='', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'naver_tracking_schedule',
            },
        ),
        migrations.CreateModel(
            name='NaverRankTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('store', '스토어'), ('product_id', '상품ID')], max_length=20)),
                ('target_value', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_targets', to='naver.naverkeyword')),
            ],
            options={
                'db_table': 'naver_rank_target',
                'unique_together': {('keyword', 'target_type', 'target_value')},
            },
        ),
        migrations.CreateModel(
            name='NaverTermAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term1', models.CharField(blank=True, default='', max_length=100)),
                ('term2', models.CharField(blank=True, default='', max_length=100)),
                ('term3', models.CharField(blank=True, default='', max_length=100)),
                ('term4', models.CharField(blank=True, default='', max_length=100)),
                ('order_weight', models.JSONField(blank=True, default=dict)),
                ('position_weight', models.JSONField(blank=True, default=dict)),
                ('name_weight', models.JSONField(blank=True, default=dict)),
                ('part_weight', models.JSONField(blank=True, default=dict)),
                ('category_priority', models.JSONField(blank=True, default=dict)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='naver.naverkeyword')),
            ],
            options={
                'db_table': 'naver_term_analysis',
            },
        ),
        migrations.CreateModel(
            name='NaverRankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_position', models.IntegerField(blank=True, null=True)),
                ('tab_type', models.CharField(default='total', max_length=20)),
                ('total_results', models.IntegerField(default=0)),
                ('found_product_name', models.CharField(blank=True, default='', max_length=500)),
                ('found_product_price', models.IntegerField(blank=True, null=True)),
                ('found_review_count', models.IntegerField(blank=True, null=True)),
                ('tracked_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='naver.naverranktarget')),
            ],
            options={
                'db_table': 'naver_rank_history',
                'indexes': [models.Index(fields=['target', 'tracked_at'], name='naver_rank__target__c4c7d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='NaverSearchSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_type', models.CharField(choices=[('total', '전체'), ('model', '가격비교'), ('checkout', '네이버페이')], max_length=20)),
                ('products', models.JSONField(default=list)),
                ('total', models.IntegerField(default=0)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='naver.naverkeyword')),
            ],
            options={
                'db_table': 'naver_search_snapshot',
                'indexes': [models.Index(fields=['keyword', 'tab_type', 'collected_at'], name='naver_searc_keyword_0a9fc0_idx')],
            },
        ),
    ]
