# Generated by Django 5.1.15 on 2026-04-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='naverrankhistory',
            name='found_product_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='naverrankhistory',
            name='found_product_image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='naverrankhistory',
            name='found_product_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
