# Generated by Django 5.1.15 on 2026-04-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0002_naverrankhistory_found_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naverranktarget',
            name='source_product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='naverranktarget',
            name='source_product_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
