# Generated by Django 5.1.15 on 2026-04-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0003_naverranktarget_source_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordEnrichCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=200, unique=True)),
                ('monthly_pc_qc', models.IntegerField(default=0)),
                ('monthly_mobile_qc', models.IntegerField(default=0)),
                ('comp_idx', models.CharField(default='', max_length=20)),
                ('product_count', models.IntegerField(default=0)),
                ('category_name', models.CharField(default='', max_length=500)),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'naver_keyword_enrich_cache',
            },
        ),
        migrations.CreateModel(
            name='CategoryKeywordCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=20)),
                ('filter_key', models.CharField(default='__', max_length=50)),
                ('ranks_json', models.JSONField(default=list)),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'naver_cat_keyword_cache',
                'indexes': [models.Index(fields=['cid', 'filter_key'], name='naver_cat_k_cid_6193e8_idx')],
                'unique_together': {('cid', 'filter_key')},
            },
        ),
    ]
