# Generated by Django 5.1.15 on 2026-04-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0004_keywordenrichcache_categorykeywordcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='naverranktarget',
            name='auto_track',
            field=models.BooleanField(default=False),
        ),
    ]
