# Generated by Django 5.1.15 on 2026-04-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0005_add_auto_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='naverranktarget',
            name='matched_product_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='naverranktarget',
            name='matched_product_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
