# Generated by Django 5.1.15 on 2026-04-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0006_add_matched_product_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='naverranktarget',
            name='auto_track_times',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
