# Generated by Django 5.1.15 on 2026-04-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0007_add_auto_track_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('report_type', models.CharField(choices=[('monthly', '월간보고서'), ('analysis', '분석')], default='monthly', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'naver_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
