# Generated by Django 5.1.15 on 2026-04-25 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0008_naverreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverPurchaseTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nv_mid', models.CharField(db_index=True, max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=500)),
                ('store_name', models.CharField(blank=True, default='', max_length=200)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('category', models.CharField(blank=True, default='', max_length=500)),
                ('source_keyword', models.CharField(blank=True, default='', max_length=200)),
                ('source_rank', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_track', models.BooleanField(default=False)),
                ('auto_track_time', models.CharField(blank=True, default='09:00', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'naver_purchase_target',
            },
        ),
        migrations.CreateModel(
            name='NaverPurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_count', models.IntegerField(blank=True, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('keep_count', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('crawl_success', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('tracked_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='naver.naverpurchasetarget')),
            ],
            options={
                'db_table': 'naver_purchase_history',
                'indexes': [models.Index(fields=['target', 'tracked_at'], name='naver_purch_target__ba5d51_idx')],
            },
        ),
    ]
