# Generated by Django 5.1.15 on 2026-04-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0009_naverpurchasetarget_naverpurchasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='naverkeyword',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
