# Generated by Django 5.1.15 on 2026-04-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0010_naverkeyword_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverCrawlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('type', models.CharField(default='info', max_length=20)),
                ('message', models.TextField()),
                ('keyword', models.CharField(blank=True, default='', max_length=200)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'naver_crawl_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='naver_crawl_timesta_d51b44_idx')],
            },
        ),
    ]
