# Generated by Django 5.1.15 on 2026-06-28 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0012_naversynonym'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemScoutProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'itemscout_product',
            },
        ),
        migrations.CreateModel(
            name='ItemScoutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_purchase', models.IntegerField(default=0)),
                ('record_date', models.DateField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'itemscout_record',
            },
        ),
        migrations.CreateModel(
            name='NaverTrackingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('store', '스토어'), ('product_id', '상품ID')], max_length=20)),
                ('target_value', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('product_name', models.CharField(blank=True, default='', max_length=500)),
                ('product_image', models.URLField(blank=True, default='', max_length=500)),
                ('product_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'naver_tracking_product',
            },
        ),
        migrations.RenameIndex(
            model_name='naversynonym',
            new_name='naver_synon_keyword_2f46ed_idx',
            old_name='naver_synon_keyword_idx',
        ),
        migrations.AddField(
            model_name='itemscoutrecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='naver.itemscoutproduct'),
        ),
        migrations.AlterUniqueTogether(
            name='navertrackingproduct',
            unique_together={('target_type', 'target_value')},
        ),
        migrations.AddField(
            model_name='naverranktarget',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets', to='naver.navertrackingproduct'),
        ),
        migrations.AddIndex(
            model_name='itemscoutrecord',
            index=models.Index(fields=['product', 'record_date'], name='itemscout_r_product_a796db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemscoutrecord',
            unique_together={('product', 'record_date')},
        ),
    ]
