# Generated by Django 5.1 on 2026-04-18 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('product_no', models.CharField(blank=True, default='', max_length=50)),
                ('store_alias', models.CharField(blank=True, default='', max_length=200)),
                ('product_name', models.CharField(blank=True, default='', max_length=500)),
                ('track_keyword', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'competitor_product',
            },
        ),
        migrations.CreateModel(
            name='CompetitorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('total_stock', models.IntegerField(default=0)),
                ('options', models.JSONField(default=list)),
                ('rank_position', models.IntegerField(blank=True, null=True)),
                ('estimated_sales', models.IntegerField(default=0)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='competitor.competitorproduct')),
            ],
            options={
                'db_table': 'competitor_snapshot',
                'indexes': [models.Index(fields=['product', 'crawled_at'], name='competitor__product_adf3e8_idx')],
            },
        ),
    ]
