# Generated by Django 5.1 on 2026-04-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitorsnapshot',
            name='options',
        ),
        migrations.RemoveField(
            model_name='competitorsnapshot',
            name='total_stock',
        ),
        migrations.AddField(
            model_name='competitorsnapshot',
            name='naver_product_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='competitorsnapshot',
            name='review_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
