# Generated by Django 5.1 on 2026-04-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0002_remove_competitorsnapshot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsnapshot',
            name='options',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='competitorsnapshot',
            name='total_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
