# Generated by Django 5.1 on 2026-04-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0003_competitorsnapshot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsnapshot',
            name='purchase_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitorsnapshot',
            name='recent_purchase_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
