from django.urls import path
from . import views

urlpatterns = [
    # Store management
    path('stores/', views.SmartStoreStoreListView.as_view()),
    path('stores/counts/', views.SmartStoreStoreCountsView.as_view()),
    path('stores/sample-excel/', views.SmartStoreStoreSampleExcelView.as_view()),
    path('stores/upload/', views.SmartStoreStoreBulkUploadView.as_view()),
    path('stores/<int:pk>/', views.SmartStoreStoreDetailView.as_view()),

    # Product management
    path('products/', views.SmartStoreProductListView.as_view()),
    path('products/search/', views.SmartStoreProductSearchView.as_view()),
    path('products/sync/', views.SmartStoreProductSyncView.as_view()),
    path('products/stats/', views.SmartStoreProductStatsView.as_view()),
    path('products/refresh-tracking/', views.SmartStoreRefreshTrackingView.as_view()),
    path('products/excel/', views.SmartStoreProductExcelView.as_view()),
    path('products/count/', views.SmartStoreProductCountView.as_view()),
    path('products/wcodes/', views.SmartStoreProductWCodesView.as_view()),
    path('products/suspend-preview/', views.SmartStoreProductSuspendPreviewView.as_view()),
    path('products/suspend/', views.SmartStoreProductSuspendView.as_view()),
    path('products/focus/', views.SmartStoreProductFocusView.as_view()),
    path('products/restock-check/', views.SmartStoreProductRestockCheckView.as_view()),
    path('products/orders/', views.SmartStoreProductOrdersView.as_view()),
    path('products/orphan-wcodes/', views.SmartStoreProductOrphanWCodesView.as_view()),
    path('products/orphan-soldout/', views.SmartStoreProductOrphanSoldoutView.as_view()),
    path('products/reconcile/', views.SmartStoreReconcileView.as_view()),
    path('products/sales-snapshot/', views.SmartStoreSalesSnapshotView.as_view()),
    path('products/sync-logs/', views.SmartStoreSyncLogView.as_view()),
    path('products/sync-logs/<int:pk>/', views.SmartStoreSyncLogDetailView.as_view()),

    # Analytics
    path('analytics/overview/', views.SmartStoreAnalyticsOverviewView.as_view()),
    path('analytics/store/<int:store_id>/', views.SmartStoreAnalyticsStoreDetailView.as_view()),
    path('analytics/business/<str:code>/', views.SmartStoreAnalyticsBusinessDetailView.as_view()),
    path('analytics/sync-categories/', views.SmartStoreAnalyticsSyncCategoriesView.as_view()),
    path('analytics/registration-limits/', views.SmartStoreRegistrationLimitView.as_view()),
    path('policy/collect/', views.SmartStorePolicyCollectView.as_view()),
    path('policy/status/', views.SmartStorePolicyStatusView.as_view()),
    path('policy/trend/', views.SmartStorePolicyTrendView.as_view()),

    # Store collection (browser automation)
    path('collect/start/', views.StoreCollectStartView.as_view()),
    path('collect/status/', views.StoreCollectStatusView.as_view()),
    path('collect/stop/', views.StoreCollectStopView.as_view()),
    path('collect/csv/', views.StoreCollectCsvView.as_view()),
    path('collect/logs/', views.StoreCollectLogsView.as_view()),

    # Product audit (전상품 API 검증)
    path('products/audit/start/', views.ProductAuditStartView.as_view()),
    path('products/audit/status/', views.ProductAuditStatusView.as_view()),
    path('products/audit/stop/', views.ProductAuditStopView.as_view()),
    path('products/audit/logs/', views.ProductAuditLogsView.as_view()),
    path('products/audit/logs/<int:pk>/', views.ProductAuditLogDetailView.as_view()),

    # Detail crawl (상세페이지 병렬 크롤링)
    path('products/detail-crawl/start/', views.DetailCrawlStartView.as_view()),
    path('products/detail-crawl/status/', views.DetailCrawlStatusView.as_view()),
    path('products/detail-crawl/stop/', views.DetailCrawlStopView.as_view()),

    # Zero margin (0마진 처리)
    path('products/zero-margin/preview/', views.ZeroMarginPreviewView.as_view()),
    path('products/zero-margin/update/', views.ZeroMarginUpdateView.as_view()),
    path('products/zero-margin/logs/', views.ZeroMarginLogsView.as_view()),
    path('products/zero-margin/logs/<int:pk>/', views.ZeroMarginLogDetailView.as_view()),

    # Product editing (상품 편집)
    path('products/<int:opno>/detail/', views.ProductFullDetailView.as_view()),
    path('products/<int:opno>/update/', views.ProductUpdateView.as_view()),
    path('products/upload-image/', views.ProductImageUploadView.as_view()),

    # 상품속성 분석 (Stage A/B/C 크롤 결과)
    path('attr/stats/', views.AttrStatsView.as_view()),
    path('attr/products/', views.AttrProductsListView.as_view()),
    path('attr/products/<str:seller_code>/', views.AttrProductDetailView.as_view()),
    path('attr/tags/top/', views.AttrTopTagsView.as_view()),
    path('attr/quality/issues/', views.AttrQualityIssuesView.as_view()),
    path('attr/categories/', views.AttrCategorySummaryView.as_view()),
    path('attr/attributes/top/', views.AttrTopAttributesView.as_view()),
    path('attr/attributes/values/', views.AttrValuesView.as_view()),

    # 빈 속성 검토 + 등록
    path('missing-attrs/summary/', views.MissingAttrsSummaryView.as_view()),
    path('missing-attrs/refresh-summary/', views.MissingAttrsRefreshSummaryView.as_view()),
    path('missing-attrs/', views.MissingAttrsListView.as_view()),
    path('missing-attrs/skus/', views.MissingAttrsSkuListView.as_view()),
    path('missing-attrs/skus/<str:seller_code>/', views.MissingAttrsForSkuView.as_view()),
    path('missing-attrs/skus/<str:seller_code>/register/', views.MissingAttrsRegisterSkuView.as_view()),
    path('missing-attrs/<int:attribute_seq>/', views.MissingAttrsDetailView.as_view()),
    path('missing-attrs/<int:attribute_seq>/skus/', views.MissingAttrsSkusView.as_view()),
    path('missing-attrs/register/', views.MissingAttrsRegisterView.as_view()),
    path('missing-attrs/register-filtered/', views.MissingAttrsRegisterFilteredView.as_view()),
    path('missing-attrs/mark/', views.MissingAttrsMarkView.as_view()),

    # 워커 대시보드
    path('workers/', views.WorkerDashboardView.as_view()),

    # 네이버 나의상품 (11번가 my_product 미러)
    path('naver-products/', views.NaverMyProductListView.as_view()),
    path('naver-products/folders/', views.NaverMyProductFolderListView.as_view()),
    path('naver-products/folders/sync/', views.NaverMyProductFolderSyncView.as_view()),
    path('naver-products/import-from-11st/', views.NaverMyProductImportFrom11stView.as_view()),
    path('naver-products/import-status/', views.NaverMyProductImportStatusView.as_view()),
    path('naver-products/<int:pk>/generate-name/', views.NaverMyProductGenerateNameView.as_view()),
    path('naver-products/<int:pk>/analyze-image/', views.NaverMyProductAnalyzeImageView.as_view()),
    path('naver-products/enqueue/', views.NaverMyProductEnqueueView.as_view()),
    path('naver-products/queue-status/', views.NaverMyProductQueueStatusView.as_view()),
    path('naver-products/dispatch-tick/', views.NaverDispatchTickView.as_view()),
    path('naver-products/folder-queue/', views.NaverFolderQueueView.as_view()),
    path('naver-products/excel/', views.NaverMyProductExcelView.as_view()),
    path('naver-products/move/', views.NaverMyProductMoveView.as_view()),
    path('naver-products/<int:pk>/', views.NaverMyProductDetailView.as_view()),
    path('naver-products/<int:pk>/clear-vision/', views.NaverMyProductClearVisionView.as_view()),
    path('naver-products/<int:pk>/keyword-pool/', views.NaverMyProductKeywordPoolView.as_view()),
    path('naver-products/<int:pk>/edit-thumb/', views.NaverMyProductEditThumbView.as_view()),
    path('naver-products/<int:pk>/variants/', views.NaverMyProductVariantListView.as_view()),
    path('naver-products/<int:pk>/variants/<int:vid>/', views.NaverMyProductVariantDetailView.as_view()),
    path('naver-products/<int:pk>/variants/<int:vid>/activate/', views.NaverMyProductVariantActivateView.as_view()),
    path('image-proxy/', __import__('smartstore.image_proxy_view', fromlist=['ImageProxyView']).ImageProxyView.as_view()),
    # 일괄 업스케일
    path('upscale/jobs/', views.NaverUpscaleJobsView.as_view()),
    path('upscale/jobs/<int:pk>/', views.NaverUpscaleJobDetailView.as_view()),
    path('upscale/jobs/<int:pk>/progress/', views.NaverUpscaleJobProgressView.as_view()),
    path('upscale/jobs/<int:pk>/<str:action>/', views.NaverUpscaleJobControlView.as_view()),
    path('upscale/workers/', views.NaverUpscaleWorkersView.as_view()),
    path('upscale/storage-stats/', views.NaverUpscaleStorageStatsView.as_view()),
    path('naver-products/<int:pk>/keyword-relevance/', views.NaverKeywordRelevanceView.as_view()),
    # AI 상품명 컨펌 학습
    path('naver-products/<int:pk>/confirm-name/', views.NaverMyProductConfirmNameView.as_view()),
    path('naver-products/<int:pk>/confirmations/', views.NaverMyProductConfirmationsView.as_view()),
    path('naver-products/<int:pk>/name-versions/', views.NaverMyProductNameVersionsView.as_view()),
    path('naver-products/<int:pk>/rollback-name/', views.NaverMyProductRollbackNameView.as_view()),
    path('name-policy/', views.NaverNamePolicyView.as_view()),
    path('name-policy/<str:category_type>/<str:keyword>/<str:policy>/', views.NaverNamePolicyDeleteView.as_view()),
    # W코드 블랙리스트 (마이/예비/오너클랜 3-DB 매칭)
    path('wcode-blacklist/', views.WcodeBlacklistView.as_view()),
    path('wcode-blacklist/upload-excel/', views.WcodeBlacklistUploadExcelView.as_view()),
    path('wcode-blacklist/match/', views.WcodeBlacklistMatchView.as_view()),
    path('wcode-blacklist/process/', views.WcodeBlacklistProcessView.as_view()),
    path('wcode-blacklist/enforce/', views.WcodeBlacklistEnforceView.as_view()),
    path('naver-keyword-related/', views.NaverKeywordRelatedView.as_view()),
    path('naver-keyword-hot/', views.NaverKeywordHotView.as_view()),
    path('brand-policy/', views.BrandPolicyListView.as_view()),
    path('brand-policy/<str:name>/', views.BrandPolicyDeleteView.as_view()),
    # 중복 검사
    path('naver-dup/by-name/', views.NaverDupByNameView.as_view()),
    path('naver-dup/by-image/', views.NaverDupByImageView.as_view()),
    path('naver-dup/by-detail/', views.NaverDupByDetailView.as_view()),
    path('naver-dup/mark/', views.NaverDupMarkView.as_view()),
    path('naver-dup/group/', views.NaverDupGroupView.as_view()),
    path('naver-products/tg-report/', views.NaverQueueTgReportView.as_view()),
    # 상품 일괄등록 (엑셀 양식)
    path('register/sets/', views.RegisterSetListView.as_view()),
    path('register/sets/<int:folder_id>/', views.RegisterSetView.as_view()),
    path('register/calc/', views.RegisterSetCalcView.as_view()),
    path('register/preview/', views.BulkRegisterPreviewView.as_view()),
    path('register/generate/', views.BulkRegisterGenerateView.as_view()),
    # 일괄등록 단계 (등록후보/작업대기 — 상태 기반)
    path('register/folder-tree/', views.RegisterFolderTreeView.as_view()),
    path('register/stage/', views.RegisterStageView.as_view()),
    path('register/select-ids/', views.RegisterSelectIdsView.as_view()),
    path('register/mark/', views.RegisterMarkView.as_view()),
    path('register/verify/', views.RegisterVerifyView.as_view()),
    path('register/sync-inspect/', views.RegisterSyncInspectView.as_view()),
    path('register/analyze-failures/', views.RegisterFailureAnalyzeView.as_view()),
    path('register/queue-excel/', views.RegisterQueueExcelView.as_view()),
    path('register/queue-excel-all/', views.RegisterQueueExcelAllView.as_view()),
    # 라이브 상품명 금지어 점검/수정
    path('live-name/scan/', views.LiveNameScanView.as_view()),
    path('live-name/fix/', views.LiveNameFixView.as_view()),
    path('bad-name/scan/', views.BadNameScanView.as_view()),
    path('bad-name/purge/', views.BadNamePurgeView.as_view()),
    path('dup-suspend/scan/', views.DupSuspendScanView.as_view()),
    path('dup-suspend/apply/', views.DupSuspendApplyView.as_view()),
    path('diagnosis/sync/', views.DiagnosisSyncView.as_view()),
    path('diagnosis/status/', views.DiagnosisStatusView.as_view()),
    path('diagnosis/results/', views.DiagnosisResultsView.as_view()),
    path('product-tag-attr-meta/', views.ProductTagAttrMetaView.as_view()),
    path('attr/auto-check/preview/', views.AttrAutoCheckPreviewView.as_view()),
    path('attr/auto-check/start/', views.AttrAutoCheckStartView.as_view()),
    path('attr/auto-check/status/', views.AttrAutoCheckStatusView.as_view()),
    path('attr/vision/start/', views.AttrVisionStartView.as_view()),
    path('attr/vision/status/', views.AttrVisionStatusView.as_view()),
    path('attr/pipeline/status/', views.AttrPipelineStatusView.as_view()),
    path('attr/sync/start/', views.AttrSyncStartView.as_view()),
    path('attr/sync/status/', views.AttrSyncStatusView.as_view()),
    path('attr/product/', views.AttrProductView.as_view()),
    path('attr/product-context/', views.AttrProductContextView.as_view()),
    path('attr/changes/recent/', views.AttrRecentChangesView.as_view()),
    path('attr/list-by-status/', views.AttrListByStatusView.as_view()),
    path('attr/needs-manual-sku/', views.AttrNeedsManualSkuView.as_view()),
    path('attr/pipeline/crawl/start/', views.AttrPipelineCrawlStartView.as_view()),
    path('attr/pipeline/stage/start/', views.AttrPipelineStageStartView.as_view()),
    path('attr/pipeline/workers/', views.AttrPipelineWorkersView.as_view()),
]
